Slide toTop-button to remove jump
subugoe/typo3-tmpl_fidaac pull request #188
Opened 2017-09-13 15:04 UTC by snaegle

Related to: AAC-666

2017-09-14 11:47 UTC, ipf requested changes
Instead of "jumping" the arrow now slowly slides. Is possible to implement that the arrow does not need extra vertical space on the site?

2017-09-14 13:41 UTC, snaegle commented
Element is sticky, so that it keeps its minimal distance above footer. Sticky elements are treated like relative elements, and than like fixed ones. 
So no, as long as we want the "sticky" behaviour, it will need vertical space.

2017-09-18 09:51 UTC, ipf approved these changes

2017-09-18 09:51 UTC, ipf commented
Sweet!

2017-09-18 09:51 UTC, merged